# Generated by Django 5.0.3 on 2024-06-08 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Articles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("link", models.TextField(unique=True)),
                ("published_at", models.DateTimeField()),
                ("content", models.TextField()),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_interesting", models.BooleanField(blank=True, null=True)),
                ("abstract", models.TextField(blank=True, null=True)),
                ("content_snippet", models.TextField(blank=True, null=True)),
                ("interesting_score", models.FloatField(blank=True, null=True)),
                ("media_url", models.TextField(default="", unique=True)),
                ("publication_name", models.TextField(default="Unknown")),
                ("sw1_score", models.FloatField(blank=True, null=True)),
                ("marx_score", models.FloatField(blank=True, null=True)),
                ("hn_score", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "articles",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserArticleInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("liked", models.BooleanField(default=False)),
                ("disliked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.articles"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "article")},
            },
        ),
    ]
