# Generated by Django 3.2 on 2024-07-12 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={},
        ),
        migrations.RemoveField(
            model_name='articles',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='is_interesting',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='publication_name',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='score',
        ),
        migrations.AddField(
            model_name='articles',
            name='is_user_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articles',
            name='sentiment',
            field=models.CharField(default='neutral', max_length=10),
        ),
        migrations.AddField(
            model_name='articles',
            name='sentiment_value',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='hn_score',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='articles',
            name='interesting_score',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='articles',
            name='link',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='marx_score',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='articles',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='articles',
            name='sw1_score',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='articles',
            table=None,
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', models.JSONField(default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RssFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='rss_feed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.rssfeed'),
        ),
    ]
